[project]
name = "py-xrd-visualize"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "oksongh", email = "oksongh@gmail.com" }
]
dependencies = ["matplotlib~=3.7.1", "numpy~=1.24.3"]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
[tool.hatch.metadata]
allow-direct-references = true
